In [1]:
# Install SQLAlchemy 1.4.4
!pip install sqlalchemy==1.4.4

# Install ipython-sql 0.4.1
!pip install ipython-sql==0.4.1

Requirement already satisfied: sqlalchemy==1.4.4 in c:\users\dr . emmanuel\anaconda3\envs\sql_new\lib\site-packages (1.4.4)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\dr . emmanuel\anaconda3\envs\sql_new\lib\site-packages (from sqlalchemy==1.4.4) (3.1.1)
Requirement already satisfied: ipython-sql==0.4.1 in c:\users\dr . emmanuel\anaconda3\envs\sql_new\lib\site-packages (0.4.1)
Requirement already satisfied: prettytable<1 in c:\users\dr . emmanuel\anaconda3\envs\sql_new\lib\site-packages (from ipython-sql==0.4.1) (0.7.2)
Requirement already satisfied: ipython>=1.0 in c:\users\dr . emmanuel\anaconda3\envs\sql_new\lib\site-packages (from ipython-sql==0.4.1) (8.30.0)
Requirement already satisfied: sqlalchemy>=0.6.7 in c:\users\dr . emmanuel\anaconda3\envs\sql_new\lib\site-packages (from ipython-sql==0.4.1) (1.4.4)
Requirement already satisfied: sqlparse in c:\users\dr . emmanuel\anaconda3\envs\sql_new\lib\site-packages (from ipython-sql==0.4.1) (0.5.3)
Requirement already satisfied: six in c:\users\dr . emmanuel\anaconda3\envs\sql_new\lib\site-packages (from ipython-sql==0.4.1) (1.16.0)
Requirement already satisfied: ipython-genutils>=0.1.0 in c:\users\dr . emmanuel\anaconda3\envs\sql_new\lib\site-packages (from ipython-sql==0.4.1) (0.2.0)
Requirement already satisfied: decorator in c:\users\dr . emmanuel\anaconda3\envs\sql_new\lib\site-packages (from ipython>=1.0->ipython-sql==0.4.1) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\dr . emmanuel\anaconda3\envs\sql_new\lib\site-packages (from ipython>=1.0->ipython-sql==0.4.1) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\users\dr . emmanuel\anaconda3\envs\sql_new\lib\site-packages (from ipython>=1.0->ipython-sql==0.4.1) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\dr . emmanuel\anaconda3\envs\sql_new\lib\site-packages (from ipython>=1.0->ipython-sql==0.4.1) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\dr . emmanuel\anaconda3\envs\sql_new\lib\site-packages (from ipython>=1.0->ipython-sql==0.4.1) (2.15.1)
Requirement already satisfied: stack-data in c:\users\dr . emmanuel\anaconda3\envs\sql_new\lib\site-packages (from ipython>=1.0->ipython-sql==0.4.1) (0.2.0)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\dr . emmanuel\anaconda3\envs\sql_new\lib\site-packages (from ipython>=1.0->ipython-sql==0.4.1) (5.14.3)
Requirement already satisfied: colorama in c:\users\dr . emmanuel\anaconda3\envs\sql_new\lib\site-packages (from ipython>=1.0->ipython-sql==0.4.1) (0.4.6)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\dr . emmanuel\anaconda3\envs\sql_new\lib\site-packages (from sqlalchemy>=0.6.7->ipython-sql==0.4.1) (3.1.1)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\dr . emmanuel\anaconda3\envs\sql_new\lib\site-packages (from jedi>=0.16->ipython>=1.0->ipython-sql==0.4.1) (0.8.4)
Requirement already satisfied: wcwidth in c:\users\dr . emmanuel\anaconda3\envs\sql_new\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=1.0->ipython-sql==0.4.1) (0.2.5)
Requirement already satisfied: executing in c:\users\dr . emmanuel\anaconda3\envs\sql_new\lib\site-packages (from stack-data->ipython>=1.0->ipython-sql==0.4.1) (0.8.3)
Requirement already satisfied: asttokens in c:\users\dr . emmanuel\anaconda3\envs\sql_new\lib\site-packages (from stack-data->ipython>=1.0->ipython-sql==0.4.1) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\dr . emmanuel\anaconda3\envs\sql_new\lib\site-packages (from stack-data->ipython>=1.0->ipython-sql==0.4.1) (0.2.2)

In [2]:
%load_ext sql

In [3]:
!pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

In [4]:
%sql mysql+pymysql://root:DSEfe0507727182@127.0.0.1:3306/beers

In [6]:
%%sql

SELECT *
FROM beers
LIMIT 5

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
5 rows affected.

[(0, 0.05, None, 1436, 'Pub Beer', 'American Pale Lager', 408, 12.0),
 (1, 0.066, None, 2265, "Devil's Cup", 'American Pale Ale (APA)', 177, 12.0),
 (2, 0.071, None, 2264, 'Rise of the Phoenix', 'American IPA', 177, 12.0),
 (3, 0.09, None, 2263, 'Sinister', 'American Double / Imperial IPA', 177, 12.0),
 (4, 0.075, None, 2262, 'Sex and Candy', 'American IPA', 177, 12.0)]

In [7]:
%%sql

SELECT *
FROM breweries
LIMIT 5

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
5 rows affected.

[(0, 'NorthGate Brewing ', 'Minneapolis', ' MN'),
 (1, 'Against the Grain Brewery', 'Louisville', ' KY'),
 (2, "Jack's Abby Craft Lagers", 'Framingham', ' MA'),
 (3, 'Mike Hess Brewing Company', 'San Diego', ' CA'),
 (4, 'Fort Point Beer Company', 'San Francisco', ' CA')]

It seems the beer dataset contains data about the beer and the Breweries contains data about the breweries producing them.

the "abv" column is the alcoholic content by volume with 0 being no alcohol and 1 being pure alcohol, the "ibu" column is known as International bittering units, which describe how bitter a drink is. 
The "id" column is the unique id of each beer and the name column contains the name of the beer. The style has to do with the Beer style (lager, ale, IPA, etc.).
 the "brewery_id" column is the Unique identifier for the brewery that produces this beer; and can use to join with brewery info, finally, the "ounce" column is the Size of beer in ounces.

## the most alcoholic beer in the data set

In [13]:
%%sql

SELECT *
FROM beers
ORDER BY abv DESC
LIMIT 10

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
10 rows affected.

[(2278, 0.128, '', 2565, 'Lee Hill Series Vol. 5 - Belgian Style Quadrupel Ale', 'Quadrupel (Quad)', 51, 19.2),
 (70, 0.125, '80.0', 2685, 'London Balling', 'English Barleywine', 1, 16.0),
 (2189, 0.12, '90.0', 2621, 'Csar', 'Russian Imperial Stout', 17, 16.0),
 (2279, 0.10400000000000001, '', 2564, 'Lee Hill Series Vol. 4 - Manhattan Style Rye Ale', 'Rye Beer', 51, 19.2),
 (1857, 0.1, '52.0', 2574, '4Beans', 'Baltic Porter', 46, 12.0),
 (1771, 0.099, '', 2249, 'Sanctified', 'Belgian Strong Pale Ale', 164, 12.0),
 (437, 0.099, '', 1033, 'Hubris Quadrupel Anniversary Ale', 'Quadrupel (Quad)', 10, 16.0),
 (2286, 0.099, '90.0', 1315, 'Upslope Imperial India Pale Ale', 'American Double / Imperial IPA', 51, 19.2),
 (1045, 0.099, '85.0', 904, 'Ex Umbris Rye Imperial Stout', 'American Double / Imperial Stout', 423, 16.0),
 (1243, 0.099, '', 2454, 'Galaxy High', 'American Double / Imperial IPA', 91, 12.0)]

The beer with the beer name Lee Hill Series and Style Quadrupel Ale	(abv = 0.128) is the most alcoholic beer in this dataset.

In [14]:
%%sql

SELECT *
FROM beers
ORDER BY abv
LIMIT 10

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
10 rows affected.

[(2266, 0.001, '', 606, 'Scotty K NA', 'Low Alcohol Beer', 522, 16.0),
 (769, 0.027000000000000003, '', 1286, 'Bikini Beer', 'American IPA', 173, 12.0),
 (1074, 0.027000000000000003, '21.0', 2482, 'Totally Radler', 'Radler', 80, 16.0),
 (2394, 0.027999999999999997, '15.0', 2306, 'Summer Brew', 'American Pilsner', 109, 12.0),
 (2027, 0.032, '13.0', 2231, 'American Light', 'Light Lager', 129, 12.0),
 (138, 0.032, '27.0', 550, 'Rocket Girl', 'KÃ¶lsch', 528, 12.0),
 (1860, 0.032, '7.0', 2266, 'Rad', 'Fruit / Vegetable Beer', 46, 16.0),
 (1460, 0.034, '6.0', 1417, 'Weiss Trash Culture', 'Berliner Weissbier', 410, 12.0),
 (190, 0.035, '45.0', 1643, 'Banner American Ale', 'American Amber / Red Ale', 318, 12.0),
 (42, 0.035, '11.0', 2545, 'Passion Fruit Prussia', 'Berliner Weissbier', 60, 12.0)]

The beer with the beer name Scotty K NA	 and StyleLow Alcohol Beer	(abv = 0.001) is the least alcoholic beer in this dataset.

In [16]:
%%sql

SELECT trim(*)
FROM beers
ORDER BY ibu DESC
LIMIT 3

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
3 rows affected.

[(1788, 0.091, '99.0', 2063, 'Count Hopula (Vault Series)', 'American Double / Imperial IPA', 30, 16.0),
 (2084, 0.062, '99.0', 12, 'Furious', 'American IPA', 61, 16.0),
 (579, 0.095, '99.0', 1647, 'Terrace Hill Double IPA', 'American Double / Imperial IPA', 350, 16.0)]

The beer with the beer name Count Hopula (Vault Series) and American Double / Imperial IPA (ibu = 99.0) is the most bitter alcoholic beer in this dataset.

In [19]:
%%sql

SELECT trim(*)
FROM beers
ORDER BY ibu DESC

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
(pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '*)\nFROM beers\nORDER BY ibu DESC' at line 1")
[SQL: SELECT trim(*)
FROM beers
ORDER BY ibu DESC]
(Background on this error at: http://sqlalche.me/e/14/f405)

In [20]:
%%sql

SELECT trim ibu
FROM beers
ORDER BY ibu DESC
LIMIT 10

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
(pymysql.err.OperationalError) (1054, "Unknown column 'trim' in 'field list'")
[SQL: SELECT trim ibu
FROM beers
ORDER BY ibu DESC
LIMIT 10]
(Background on this error at: http://sqlalche.me/e/14/e3q8)

In [21]:
%%sql

SELECT trim(ibu)
FROM beers
ORDER BY ibu DESC
LIMIT 10

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
10 rows affected.

[('99.0',),
 ('99.0',),
 ('99.0',),
 ('99.0',),
 ('98.0',),
 ('98.0',),
 ('98.0',),
 ('98.0',),
 ('97.0',),
 ('95.0',)]

In [22]:
%%sql
DESCRIBE beers

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
8 rows affected.

[('SerialN', 'int', 'YES', '', None, ''),
 ('abv', 'double', 'YES', '', None, ''),
 ('ibu', 'text', 'YES', '', None, ''),
 ('id', 'int', 'YES', '', None, ''),
 ('beers_name', 'text', 'YES', '', None, ''),
 ('style', 'text', 'YES', '', None, ''),
 ('brewery_id', 'int', 'YES', 'MUL', None, ''),
 ('ounces', 'double', 'YES', '', None, '')]

In [25]:
%%sql
ALTER TABLE beers
MODIFY ibu DOUBLE;

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
(pymysql.err.DataError) (1265, "Data truncated for column 'ibu' at row 1")
[SQL: ALTER TABLE beers
MODIFY ibu DOUBLE;]
(Background on this error at: http://sqlalche.me/e/14/9h9h)

In [33]:
%%sql
SELECT ibu 
FROM beers 
WHERE CAST(ibu AS DOUBLE) IS NULL OR ibu = ''
LIMIT 5;

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
5 rows affected.

[(None,), (None,), (None,), (None,), (None,)]

In [29]:
%%sql

SELECT *
FROM beers
LIMIT 5

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
5 rows affected.

[(0, 0.05, None, 1436, 'Pub Beer', 'American Pale Lager', 408, 12.0),
 (1, 0.066, None, 2265, "Devil's Cup", 'American Pale Ale (APA)', 177, 12.0),
 (2, 0.071, None, 2264, 'Rise of the Phoenix', 'American IPA', 177, 12.0),
 (3, 0.09, None, 2263, 'Sinister', 'American Double / Imperial IPA', 177, 12.0),
 (4, 0.075, None, 2262, 'Sex and Candy', 'American IPA', 177, 12.0)]

In [30]:
%%sql

SELECT trim(ibu)
FROM beers
ORDER BY ibu DESC
LIMIT 10

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
10 rows affected.

[('99.0',),
 ('99.0',),
 ('99.0',),
 ('99.0',),
 ('98.0',),
 ('98.0',),
 ('98.0',),
 ('98.0',),
 ('97.0',),
 ('95.0',)]

In [31]:
%%sql
ALTER TABLE beers
MODIFY ibu DOUBLE;

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
2348 rows affected.

ResourceClosedError: This result object does not return rows. It has been closed automatically.

In [32]:
%%sql

SELECT *
FROM beers
ORDER BY ibu DESC
LIMIT 10

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
10 rows affected.

[(147, 0.08199999999999999, 138.0, 980, 'Bitter Bitch Imperial IPA', 'American Double / Imperial IPA', 374, 12.0),
 (2390, 0.059000000000000004, 135.0, 1676, 'Troopers Alley IPA', 'American IPA', 344, 12.0),
 (525, 0.09, 130.0, 2067, 'Dead-Eye DIPA', 'American Double / Imperial IPA', 230, 16.0),
 (594, 0.08900000000000001, 126.0, 2440, 'Bay of Bengal Double IPA (2014)', 'American Double / Imperial IPA', 99, 12.0),
 (2144, 0.08, 120.0, 1111, 'Heady Topper', 'American Double / Imperial IPA', 272, 16.0),
 (2145, 0.08, 120.0, 379, 'Heady Topper', 'American Double / Imperial IPA', 272, 16.0),
 (2081, 0.09699999999999999, 120.0, 15, 'Abrasive Ale', 'American Double / Imperial IPA', 61, 16.0),
 (474, 0.09, 118.0, 2123, 'More Cowbell', 'American Double / Imperial IPA', 214, 16.0),
 (150, 0.075, 115.0, 2503, 'Hop A-Peel', 'American Double / Imperial IPA', 72, 16.0),
 (2191, 0.085, 115.0, 1449, 'Overlord Imperial IPA', 'American Double / Imperial IPA', 17, 16.0)]

The beer with the beer name Bitter Bitch Imperial IP and American Double / Imperial IPA (ibu = 138.0) is the most bitter alcoholic beer in this dataset.

In [10]:
%%sql
SELECT *
FROM breweries
LIMIT 10

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
10 rows affected.

[(0, 'NorthGate Brewing ', 'Minneapolis', ' MN'),
 (1, 'Against the Grain Brewery', 'Louisville', ' KY'),
 (2, "Jack's Abby Craft Lagers", 'Framingham', ' MA'),
 (3, 'Mike Hess Brewing Company', 'San Diego', ' CA'),
 (4, 'Fort Point Beer Company', 'San Francisco', ' CA'),
 (5, 'COAST Brewing Company', 'Charleston', ' SC'),
 (6, 'Great Divide Brewing Company', 'Denver', ' CO'),
 (7, 'Tapistry Brewing', 'Bridgman', ' MI'),
 (8, 'Big Lake Brewing', 'Holland', ' MI'),
 (9, 'The Mitten Brewing Company', 'Grand Rapids', ' MI')]

In [12]:
%%sql

SELECT beers.ibu, beers.brewery_id, beers.beers_name, breweries.brewery_id, breweries.brewery_name
FROM beers
INNER JOIN breweries
ON beers.brewery_id = breweries.brewery_id
ORDER BY beers.ibu DESC
LIMIT 5

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
5 rows affected.

[(138.0, 374, 'Bitter Bitch Imperial IPA', 374, 'Astoria Brewing Company'),
 (135.0, 344, 'Troopers Alley IPA', 344, 'Wolf Hills Brewing Company'),
 (130.0, 230, 'Dead-Eye DIPA', 230, 'Cape Ann Brewing Company'),
 (126.0, 99, 'Bay of Bengal Double IPA (2014)', 99, 'Christian Moerlein Brewing Company'),
 (120.0, 61, 'Abrasive Ale', 61, 'Surly Brewing Company')]

The beer with the beer name Bitter Bitch Imperial IPA and and produced by the Astoria Brewing Company (ibu = 138.0) is the most bitter alcoholic beer in this combined data sets.

In [13]:
%%sql

SELECT be.ibu, be.brewery_id, be.beers_name, br.brewery_id, br.brewery_name
FROM beers AS be
INNER JOIN breweries AS br
ON be.brewery_id = br.brewery_id
ORDER BY be.ibu DESC
LIMIT 5

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
5 rows affected.

[(138.0, 374, 'Bitter Bitch Imperial IPA', 374, 'Astoria Brewing Company'),
 (135.0, 344, 'Troopers Alley IPA', 344, 'Wolf Hills Brewing Company'),
 (130.0, 230, 'Dead-Eye DIPA', 230, 'Cape Ann Brewing Company'),
 (126.0, 99, 'Bay of Bengal Double IPA (2014)', 99, 'Christian Moerlein Brewing Company'),
 (120.0, 61, 'Abrasive Ale', 61, 'Surly Brewing Company')]

The above was repeated in the alliance format with be representing beers and br rep breweries. Hence, they were replaced in the synthax

In [3]:
%%sql

SELECT DISTINCT (city)
FROM breweries
LIMIT 10

Environment variable $DATABASE_URL not set, and no connect string given.
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

In [30]:
%%sql

SELECT DISTINCT (state)
FROM breweries
LIMIT 10

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
10 rows affected.

[(' MN',),
 (' KY',),
 (' MA',),
 (' CA',),
 (' SC',),
 (' CO',),
 (' MI',),
 (' IN',),
 (' TX',),
 (' AZ',)]

In [16]:
%%sql

SELECT *
FROM beers
LIMIT 2

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
2 rows affected.

[(0, 0.05, None, 1436, 'Pub Beer', 'American Pale Lager', 408, 12.0),
 (1, 0.066, None, 2265, "Devil's Cup", 'American Pale Ale (APA)', 177, 12.0)]

In [4]:
%%sql

SELECT be.brewery_id, br.brewery_id, br.brewery_name, be.beers_name, be.style, br.state
FROM beers AS be
INNER JOIN breweries AS br
ON be.brewery_id = br.brewery_id
WHERE state LIKE '%CA%';

Environment variable $DATABASE_URL not set, and no connect string given.
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

In [31]:
%%sql

SELECT br.brewery_id, br.brewery_name, be.beers_name, be.style, br.state
FROM beers AS be
INNER JOIN breweries AS br
ON be.brewery_id = br.brewery_id
WHERE state LIKE "%CA%";

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
182 rows affected.

[(3, 'Mike Hess Brewing Company', 'Habitus (2014)', 'American Double / Imperial IPA', ' CA'),
 (3, 'Mike Hess Brewing Company', 'Solis', 'American IPA', ' CA'),
 (3, 'Mike Hess Brewing Company', 'Jucundus', 'Wheat Ale', ' CA'),
 (3, 'Mike Hess Brewing Company', 'Habitus', 'American Double / Imperial IPA', ' CA'),
 (3, 'Mike Hess Brewing Company', 'Grazias', 'Cream Ale', ' CA'),
 (3, 'Mike Hess Brewing Company', 'Claritas', 'KÃ¶lsch', ' CA'),
 (4, 'Fort Point Beer Company', 'Park', 'American Pale Wheat Ale', ' CA'),
 (4, 'Fort Point Beer Company', 'Westfalia', 'American Amber / Red Ale', ' CA'),
 (4, 'Fort Point Beer Company', 'KSA', 'KÃ¶lsch', ' CA'),
 (4, 'Fort Point Beer Company', 'Villager', 'American IPA', ' CA'),
 (33, "The Dudes' Brewing Company", 'Surfrider', 'American Pale Ale (APA)', ' CA'),
 (33, "The Dudes' Brewing Company", 'Kolschtal Eddy', 'KÃ¶lsch', ' CA'),
 (33, "The Dudes' Brewing Company", 'South Bay Session IPA', 'American IPA', ' CA'),
 (33, "The Dudes' Brewing Company", "Grandma's Pecan", 'English Brown Ale', ' CA'),
 (33, "The Dudes' Brewing Company", 'Double Trunk', 'American Double / Imperial IPA', ' CA'),
 (34, 'Ballast Point Brewing Company', 'Grapefruit Sculpin', 'American IPA', ' CA'),
 (34, 'Ballast Point Brewing Company', 'Even Keel', 'American IPA', ' CA'),
 (34, 'Ballast Point Brewing Company', 'Ballast Point Pale Ale', 'KÃ¶lsch', ' CA'),
 (34, 'Ballast Point Brewing Company', 'Big Eye India Pale Ale', 'American IPA', ' CA'),
 (34, 'Ballast Point Brewing Company', 'Longfin Lager', 'Munich Helles Lager', ' CA'),
 (34, 'Ballast Point Brewing Company', 'Sculpin IPA', 'American IPA', ' CA'),
 (35, 'Anchor Brewing Company', 'Liberty Ale', 'American IPA', ' CA'),
 (35, 'Anchor Brewing Company', 'IPA', 'American IPA', ' CA'),
 (35, 'Anchor Brewing Company', 'Summer Wheat', 'American Pale Wheat Ale', ' CA'),
 (35, 'Anchor Brewing Company', 'California Lager', 'American Amber / Red Lager', ' CA'),
 (35, 'Anchor Brewing Company', 'Brotherhood Steam', 'California Common / Steam Beer', ' CA'),
 (36, 'Figueroa Mountain Brewing Company', 'Weiss Weiss Baby', 'Kristalweizen', ' CA'),
 (36, 'Figueroa Mountain Brewing Company', 'Czech Yo Self', 'Czech Pilsener', ' CA'),
 (36, 'Figueroa Mountain Brewing Company', 'FMB 101', 'KÃ¶lsch', ' CA'),
 (48, 'Firestone Walker Brewing Company', 'Easy Jack', 'American IPA', ' CA'),
 (48, 'Firestone Walker Brewing Company', 'Union Jack', 'American IPA', ' CA'),
 (48, 'Firestone Walker Brewing Company', 'Pivo Pils', 'German Pilsener', ' CA'),
 (48, 'Firestone Walker Brewing Company', '805 Blonde Ale', 'American Blonde Ale', ' CA'),
 (48, 'Firestone Walker Brewing Company', '805', 'American Blonde Ale', ' CA'),
 (78, 'Speakasy Ales & Lagers', 'Baby Daddy Session IPA', 'American IPA', ' CA'),
 (83, 'Sierra Nevada Brewing Company', 'Nooner', 'German Pilsener', ' CA'),
 (83, 'Sierra Nevada Brewing Company', 'Torpedo', 'American IPA', ' CA'),
 (83, 'Sierra Nevada Brewing Company', 'Yonder Bock', 'Maibock / Helles Bock', ' CA'),
 (83, 'Sierra Nevada Brewing Company', 'CANfusion Rye Bock', 'Rye Beer', ' CA'),
 (83, 'Sierra Nevada Brewing Company', 'Sierra Nevada Pale Ale', 'American Pale Ale (APA)', ' CA'),
 (83, 'Sierra Nevada Brewing Company', 'Old Chico Crystal Wheat', 'American Pale Wheat Ale', ' CA'),
 (83, 'Sierra Nevada Brewing Company', 'Summerfest', 'Czech Pilsener', ' CA'),
 (83, 'Sierra Nevada Brewing Company', 'Torpedo', 'American IPA', ' CA'),
 (83, 'Sierra Nevada Brewing Company', 'Sierra Nevada Pale Ale', 'American Pale Ale (APA)', ' CA'),
 (98, 'Mission Brewery', 'Cortez Gold', 'Belgian Pale Ale', ' CA'),
 (98, 'Mission Brewery', 'Mission IPA', 'American IPA', ' CA'),
 (98, 'Mission Brewery', 'El Conquistador Extra Pale Ale', 'American Pale Ale (APA)', ' CA'),
 (98, 'Mission Brewery', 'Shipwrecked Double IPA', 'American Double / Imperial IPA', ' CA'),
 (111, 'Mother Earth Brew Company', "Cali Creamin'", 'Cream Ale', ' CA'),
 (112, 'Black Market Brewing Company', 'Deception', 'American Blonde Ale', ' CA'),
 (112, 'Black Market Brewing Company', 'Blackmarket Rye IPA', 'American IPA', ' CA'),
 (112, 'Black Market Brewing Company', 'Black Market Hefeweizen', 'Hefeweizen', ' CA'),
 (112, 'Black Market Brewing Company', 'Aftermath Pale Ale', 'American Pale Ale (APA)', ' CA'),
 (171, 'Anderson Valley Brewing Company', 'Blood Orange Gose', 'Gose', ' CA'),
 (171, 'Anderson Valley Brewing Company', "Keebarlin' Pale Ale", 'American Pale Ale (APA)', ' CA'),
 (171, 'Anderson Valley Brewing Company', 'the Kimmie, the Yink and the Holy Gose', 'Gose', ' CA'),
 (171, 'Anderson Valley Brewing Company', "Fall Hornin'", 'Pumpkin Ale', ' CA'),
 (171, 'Anderson Valley Brewing Company', 'Barney Flats Oatmeal Stout', 'Oatmeal Stout', ' CA'),
 (171, 'Anderson Valley Brewing Company', 'Summer Solstice', 'Cream Ale', ' CA'),
 (171, 'Anderson Valley Brewing Company', "Hop Ottin' IPA", 'American IPA', ' CA'),
 (171, 'Anderson Valley Brewing Company', 'Boont Amber Ale', 'American Amber / Red Ale', ' CA'),
 (171, 'Anderson Valley Brewing Company', 'Barney Flats Oatmeal Stout', 'Oatmeal Stout', ' CA'),
 (171, 'Anderson Valley Brewing Company', 'El Steinber Dark Lager', 'Vienna Lager', ' CA'),
 (171, 'Anderson Valley Brewing Company', 'Boont Amber Ale (2010)', 'American Amber / Red Ale', ' CA'),
 (171, 'Anderson Valley Brewing Company', 'Summer Solstice Cerveza Crema (2009)', 'Cream Ale', ' CA'),
 (171, 'Anderson Valley Brewing Company', 'Barney Flats Oatmeal Stout (2012)', 'Oatmeal Stout', ' CA'),
 (171, 'Anderson Valley Brewing Company', 'Winter Solstice', 'Winter Warmer', ' CA'),
 (171, 'Anderson Valley Brewing Company', "Hop Ottin' IPA (2011)", 'American IPA', ' CA'),
 (171, 'Anderson Valley Brewing Company', 'Boont Amber Ale (2011)', 'American Amber / Red Ale', ' CA'),
 (171, 'Anderson Valley Brewing Company', 'Summer Solstice (2011)', 'Cream Ale', ' CA'),
 (171, 'Anderson Valley Brewing Company', 'Poleeko Gold Pale Ale (2009)', 'American Pale Ale (APA)', ' CA'),
 (209, 'Modern Times Beer', 'City of the Sun', 'American IPA', ' CA'),
 (209, 'Modern Times Beer', 'Booming Rollers', 'American IPA', ' CA'),
 (209, 'Modern Times Beer', 'Oneida', 'American Pale Ale (APA)', ' CA'),
 (209, 'Modern Times Beer', 'Aurora ', 'American Amber / Red Ale', ' CA'),
 (209, 'Modern Times Beer', 'Lomaland', 'Saison / Farmhouse Ale', ' CA'),
 (209, 'Modern Times Beer', 'Fortunate Islands', 'American Pale Wheat Ale', ' CA'),
 (209, 'Modern Times Beer', 'Black House', 'American Stout', ' CA'),
 (209, 'Modern Times Beer', 'Blazing World', 'American Amber / Red Ale', ' CA'),
 (225, 'Refuge Brewery', 'Blood Orange Wit', 'Witbier', ' CA'),
 (240, 'Golden Road Brewing', 'Might As Well IPL', 'American Pale Lager', ' CA'),
 (240, 'Golden Road Brewing', 'Saison Pamplemousse', 'Saison / Farmhouse Ale', ' CA'),
 (240, 'Golden Road Brewing', '2020 IPA', 'American IPA', ' CA'),
 (240, 'Golden Road Brewing', 'Wolf Among Weeds IPA', 'American IPA', ' CA'),
 (240, 'Golden Road Brewing', 'Better Weather IPA', 'American IPA', ' CA'),
 (240, 'Golden Road Brewing', 'Point the Way IPA', 'American IPA', ' CA'),
 (240, 'Golden Road Brewing', 'Golden Road Hefeweizen', 'Hefeweizen', ' CA'),
 (240, 'Golden Road Brewing', 'Heal the Bay IPA', 'American IPA', ' CA'),
 (240, 'Golden Road Brewing', 'Point the Way IPA', 'American IPA', ' CA'),
 (240, 'Golden Road Brewing', 'Cabrillo KÃ¶lsch', 'KÃ¶lsch', ' CA'),
 (240, 'Golden Road Brewing', 'Get Up Offa That Brown', 'American Brown Ale', ' CA'),
 (240, 'Golden Road Brewing', 'Burning Bush Smoked IPA', 'American IPA', ' CA'),
 (240, 'Golden Road Brewing', 'Wolf Among Weeds IPA (2012)', 'American IPA', ' CA'),
 (240, 'Golden Road Brewing', 'Point the Way IPA (2012)', 'American IPA', ' CA'),
 (240, 'Golden Road Brewing', 'Golden Road Hefeweizen (2012)', 'Hefeweizen', ' CA'),
 (252, 'Santa Cruz Mountain Brewing', 'Giant DIPA', 'American Double / Imperial IPA', ' CA'),
 (252, 'Santa Cruz Mountain Brewing', 'Dread Brown Ale', 'American Brown Ale', ' CA'),
 (252, 'Santa Cruz Mountain Brewing', 'Casinos IPA', 'English India Pale Ale (IPA)', ' CA'),
 (280, 'Headlands Brewing Company', 'Groupe G', 'Belgian IPA', ' CA'),
 (280, 'Headlands Brewing Company', 'Pt. Bonita Rustic Lager', 'American Pale Lager', ' CA'),
 (280, 'Headlands Brewing Company', 'Hill 88 Double IPA', 'American Double / Imperial IPA', ' CA'),
 (288, 'Saint Archer Brewery', 'Saint Archer White Ale', 'Witbier', ' CA'),
 (288, 'Saint Archer Brewery', 'Saint Archer IPA', 'American IPA', ' CA'),
 (288, 'Saint Archer Brewery', 'Saint Archer Pale Ale', 'American Pale Ale (APA)', ' CA'),
 (288, 'Saint Archer Brewery', 'Saint Archer Blonde', 'KÃ¶lsch', ' CA'),
 (310, 'Pine Street Brewery', 'Black Bay Milk Stout', 'Milk / Sweet Stout', ' CA'),
 (310, 'Pine Street Brewery', 'Atom Splitter Pale Ale', 'American Pale Ale (APA)', ' CA'),
 (320, 'Claremont Craft Ales', 'Jacaranada Rye IPA', 'American IPA', ' CA'),
 (333, "David's Ale Works", 'Sprocket Blonde Ale (2006)', 'American Blonde Ale', ' CA'),
 (333, "David's Ale Works", 'Sprocket Pale Ale (2006)', 'American Pale Ale (APA)', ' CA'),
 (346, 'Manzanita Brewing Company', 'Chaotic Double IPA', 'American Double / Imperial IPA', ' CA'),
 (346, 'Manzanita Brewing Company', 'Manzanita IPA', 'American IPA', ' CA'),
 (346, 'Manzanita Brewing Company', 'Riverwalk Blonde Ale', 'American Blonde Ale', ' CA'),
 (346, 'Manzanita Brewing Company', 'Gillespie Brown Ale', 'American Brown Ale', ' CA'),
 (346, 'Manzanita Brewing Company', 'Manzanita Pale Ale', 'American Pale Ale (APA)', ' CA'),
 (350, 'Central Coast Brewing Company', 'Chai Ale', 'Herbed / Spiced Beer', ' CA'),
 (350, 'Central Coast Brewing Company', 'Lucky Day IPA', 'American IPA', ' CA'),
 (350, 'Central Coast Brewing Company', 'Terrace Hill Double IPA', 'American Double / Imperial IPA', ' CA'),
 (350, 'Central Coast Brewing Company', 'Catch 23', 'American Black Ale', ' CA'),
 (368, '21st Amendment Brewery', 'He Said Baltic-Style Porter', 'Baltic Porter', ' CA'),
 (368, '21st Amendment Brewery', 'He Said Belgian-Style Tripel', 'Tripel', ' CA'),
 (368, '21st Amendment Brewery', 'Lower De Boom', 'American Barleywine', ' CA'),
 (368, '21st Amendment Brewery', 'Fireside Chat', 'Winter Warmer', ' CA'),
 (368, '21st Amendment Brewery', 'Marooned On Hog Island', 'American Stout', ' CA'),
 (368, '21st Amendment Brewery', 'Bitter American', 'American Pale Ale (APA)', ' CA'),
 (368, '21st Amendment Brewery', 'Hell or High Watermelon Wheat (2009)', 'Fruit / Vegetable Beer', ' CA'),
 (368, '21st Amendment Brewery', 'Hell or High Watermelon Wheat (2009)', 'Fruit / Vegetable Beer', ' CA'),
 (368, '21st Amendment Brewery', '21st Amendment Watermelon Wheat Beer (2006)', 'Fruit / Vegetable Beer', ' CA'),
 (368, '21st Amendment Brewery', '21st Amendment IPA (2006)', 'American IPA', ' CA'),
 (368, '21st Amendment Brewery', 'Brew Free! or Die IPA (2008)', 'American IPA', ' CA'),
 (368, '21st Amendment Brewery', 'Brew Free! or Die IPA (2009)', 'American IPA', ' CA'),
 (368, '21st Amendment Brewery', 'Special Edition: Allies Win The War!', 'English Strong Ale', ' CA'),
 (368, '21st Amendment Brewery', 'Hop Crisis', 'American Double / Imperial IPA', ' CA'),
 (368, '21st Amendment Brewery', 'Bitter American (2011)', 'American Pale Ale (APA)', ' CA'),
 (368, '21st Amendment Brewery', 'Fireside Chat (2010)', 'Winter Warmer', ' CA'),
 (368, '21st Amendment Brewery', 'Back in Black', 'American Black Ale', ' CA'),
 (368, '21st Amendment Brewery', "Monk's Blood", 'Belgian Dark Ale', ' CA'),
 (368, '21st Amendment Brewery', 'Brew Free! or Die IPA', 'American IPA', ' CA'),
 (368, '21st Amendment Brewery', 'Hell or High Watermelon Wheat', 'Fruit / Vegetable Beer', ' CA'),
 (370, 'Pizza Port Brewing Company', 'PONTO S.I.P.A.', 'American IPA', ' CA'),
 (370, 'Pizza Port Brewing Company', 'Chronic Ale', 'American Amber / Red Ale', ' CA'),
 (370, 'Pizza Port Brewing Company', "Swami's India Pale Ale", 'American IPA', ' CA'),
 (397, 'Ruhstaller Beer Company', '1881 California Red', 'American Amber / Red Ale', ' CA'),
 (397, 'Ruhstaller Beer Company', 'CAPT Black IPA', 'American Black Ale', ' CA'),
 (397, 'Ruhstaller Beer Company', "Ruhstaller's Gilt Edge Lager Beer", 'American Amber / Red Lager', ' CA'),
 (397, 'Ruhstaller Beer Company', 'CAPT Black IPA', 'American Black Ale', ' CA'),
 (397, 'Ruhstaller Beer Company', '1881 California Red Ale', 'American Amber / Red Ale', ' CA'),
 (423, 'Hess Brewing Company', 'Grazias', 'Cream Ale', ' CA'),
 (423, 'Hess Brewing Company', 'Habitus IPA', 'American IPA', ' CA'),
 (423, 'Hess Brewing Company', 'Ex Umbris Rye Imperial Stout', 'American Double / Imperial Stout', ' CA'),
 (432, 'Seabright Brewery', 'Blur India Pale Ale', 'American IPA', ' CA'),
 (448, 'Mavericks Beer Company', 'Pit Stop Chocolate Porter', 'American Porter', ' CA'),
 (448, 'Mavericks Beer Company', 'Pace Setter Belgian Style Wit', 'Witbier', ' CA'),
 (448, 'Mavericks Beer Company', 'Back in the Saddle Rye Pale Ale', 'American Pale Ale (APA)', ' CA'),
 (449, 'TailGate Beer', 'Dodgy Knight Imperial IPA', 'American Double / Imperial IPA', ' CA'),
 (449, 'TailGate Beer', 'TailGate Saison', 'Saison / Farmhouse Ale', ' CA'),
 (449, 'TailGate Beer', 'TailGate IPA', 'American IPA', ' CA'),
 (449, 'TailGate Beer', 'TailGate IPA', 'American IPA', ' CA'),
 (449, 'TailGate Beer', 'TailGate Hefeweizen', 'Hefeweizen', ' CA'),
 (449, 'TailGate Beer', 'Blacktop Blonde', 'American Blonde Ale', ' CA'),
 (449, 'TailGate Beer', 'Blacktop Blonde', 'American Blonde Ale', ' CA'),
 (449, 'TailGate Beer', 'TailGate Hefeweizen', 'Hefeweizen', ' CA'),
 (461, 'Armstrong Brewing Company', "Mo's Gose", 'Gose', ' CA'),
 (476, 'Hangar 24 Craft Brewery', 'Orange Wheat', 'Fruit / Vegetable Beer', ' CA'),
 (476, 'Hangar 24 Craft Brewery', 'Hangar 24 Helles Lager', 'Munich Helles Lager', ' CA'),
 (491, "Devil's Canyon Brewery", 'Deadicated Amber', 'American Amber / Red Ale', ' CA'),
 (491, "Devil's Canyon Brewery", 'California Sunshine Rye IPA', 'American IPA', ' CA'),
 (491, "Devil's Canyon Brewery", 'Full Boar Scotch Ale', 'Scotch Ale / Wee Heavy', ' CA'),
 (514, 'Monkey Paw Pub & Brewery', 'Sweet Georgia Brown', 'American Brown Ale', ' CA'),
 (514, 'Monkey Paw Pub & Brewery', "Rich Man's IIPA", 'American Double / Imperial IPA', ' CA'),
 (514, 'Monkey Paw Pub & Brewery', 'Monkey Paw Oatmeal Pale Ale', 'American Pale Ale (APA)', ' CA'),
 (517, "Butcher's Brewing", 'Mucho Aloha Hawaiian Pale Ale', 'American Pale Ale (APA)', ' CA'),
 (522, 'Uncommon Brewers', 'Scotty K NA', 'Low Alcohol Beer', ' CA'),
 (522, 'Uncommon Brewers', 'Bacon Brown Ale', 'American Brown Ale', ' CA'),
 (522, 'Uncommon Brewers', 'Golden State Ale', 'Belgian Pale Ale', ' CA'),
 (522, 'Uncommon Brewers', 'Baltic Porter', 'Baltic Porter', ' CA'),
 (522, 'Uncommon Brewers', 'Siamese twin', 'Dubbel', ' CA'),
 (534, 'Mammoth Brewing Company', 'High Country Pilsner (Current)', 'German Pilsener', ' CA'),
 (534, 'Mammoth Brewing Company', 'Epic IPA', 'American IPA', ' CA'),
 (534, 'Mammoth Brewing Company', 'Golden Trout Pilsner', 'German Pilsener', ' CA'),
 (534, 'Mammoth Brewing Company', 'Real McCoy Amber Ale (Current)', 'American Amber / Red Ale', ' CA'),
 (555, 'Ukiah Brewing Company', 'Pilsner Ukiah', 'German Pilsener', ' CA')]

NOTE: There are 182 beer

In [22]:
%%sql

SELECT DISTINCT be.beers_name, br.brewery_id, br.brewery_name, be.style, br.state
FROM beers AS be
INNER JOIN breweries AS br
ON be.brewery_id = br.brewery_id
WHERE state LIKE "%CA%";

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
173 rows affected.
(pymysql.err.ProgrammingError) (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 5' at line 1")
[SQL: LIMIT 5]
(Background on this error at: http://sqlalche.me/e/14/f405)

The distribution of the various beer names in CA in the join data of breweries and beers. 
Table appearing in the order of placement/arrangement of what were selected.
The DISTINCT FUNCTION ANLY AFFECTED THE BEER NAME. Thus, reducing the number of rows from 182 to 173.

In [36]:
%%sql

SELECT DISTINCT br.brewery_name, be.beers_name, br.brewery_id, be.style, br.state
FROM beers AS be
INNER JOIN breweries AS br
ON be.brewery_id = br.brewery_id
WHERE state LIKE "%CA%";

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
173 rows affected.

[('Mike Hess Brewing Company', 'Habitus (2014)', 3, 'American Double / Imperial IPA', ' CA'),
 ('Mike Hess Brewing Company', 'Solis', 3, 'American IPA', ' CA'),
 ('Mike Hess Brewing Company', 'Jucundus', 3, 'Wheat Ale', ' CA'),
 ('Mike Hess Brewing Company', 'Habitus', 3, 'American Double / Imperial IPA', ' CA'),
 ('Mike Hess Brewing Company', 'Grazias', 3, 'Cream Ale', ' CA'),
 ('Mike Hess Brewing Company', 'Claritas', 3, 'KÃ¶lsch', ' CA'),
 ('Fort Point Beer Company', 'Park', 4, 'American Pale Wheat Ale', ' CA'),
 ('Fort Point Beer Company', 'Westfalia', 4, 'American Amber / Red Ale', ' CA'),
 ('Fort Point Beer Company', 'KSA', 4, 'KÃ¶lsch', ' CA'),
 ('Fort Point Beer Company', 'Villager', 4, 'American IPA', ' CA'),
 ("The Dudes' Brewing Company", 'Surfrider', 33, 'American Pale Ale (APA)', ' CA'),
 ("The Dudes' Brewing Company", 'Kolschtal Eddy', 33, 'KÃ¶lsch', ' CA'),
 ("The Dudes' Brewing Company", 'South Bay Session IPA', 33, 'American IPA', ' CA'),
 ("The Dudes' Brewing Company", "Grandma's Pecan", 33, 'English Brown Ale', ' CA'),
 ("The Dudes' Brewing Company", 'Double Trunk', 33, 'American Double / Imperial IPA', ' CA'),
 ('Ballast Point Brewing Company', 'Grapefruit Sculpin', 34, 'American IPA', ' CA'),
 ('Ballast Point Brewing Company', 'Even Keel', 34, 'American IPA', ' CA'),
 ('Ballast Point Brewing Company', 'Ballast Point Pale Ale', 34, 'KÃ¶lsch', ' CA'),
 ('Ballast Point Brewing Company', 'Big Eye India Pale Ale', 34, 'American IPA', ' CA'),
 ('Ballast Point Brewing Company', 'Longfin Lager', 34, 'Munich Helles Lager', ' CA'),
 ('Ballast Point Brewing Company', 'Sculpin IPA', 34, 'American IPA', ' CA'),
 ('Anchor Brewing Company', 'Liberty Ale', 35, 'American IPA', ' CA'),
 ('Anchor Brewing Company', 'IPA', 35, 'American IPA', ' CA'),
 ('Anchor Brewing Company', 'Summer Wheat', 35, 'American Pale Wheat Ale', ' CA'),
 ('Anchor Brewing Company', 'California Lager', 35, 'American Amber / Red Lager', ' CA'),
 ('Anchor Brewing Company', 'Brotherhood Steam', 35, 'California Common / Steam Beer', ' CA'),
 ('Figueroa Mountain Brewing Company', 'Weiss Weiss Baby', 36, 'Kristalweizen', ' CA'),
 ('Figueroa Mountain Brewing Company', 'Czech Yo Self', 36, 'Czech Pilsener', ' CA'),
 ('Figueroa Mountain Brewing Company', 'FMB 101', 36, 'KÃ¶lsch', ' CA'),
 ('Firestone Walker Brewing Company', 'Easy Jack', 48, 'American IPA', ' CA'),
 ('Firestone Walker Brewing Company', 'Union Jack', 48, 'American IPA', ' CA'),
 ('Firestone Walker Brewing Company', 'Pivo Pils', 48, 'German Pilsener', ' CA'),
 ('Firestone Walker Brewing Company', '805 Blonde Ale', 48, 'American Blonde Ale', ' CA'),
 ('Firestone Walker Brewing Company', '805', 48, 'American Blonde Ale', ' CA'),
 ('Speakasy Ales & Lagers', 'Baby Daddy Session IPA', 78, 'American IPA', ' CA'),
 ('Sierra Nevada Brewing Company', 'Nooner', 83, 'German Pilsener', ' CA'),
 ('Sierra Nevada Brewing Company', 'Torpedo', 83, 'American IPA', ' CA'),
 ('Sierra Nevada Brewing Company', 'Yonder Bock', 83, 'Maibock / Helles Bock', ' CA'),
 ('Sierra Nevada Brewing Company', 'CANfusion Rye Bock', 83, 'Rye Beer', ' CA'),
 ('Sierra Nevada Brewing Company', 'Sierra Nevada Pale Ale', 83, 'American Pale Ale (APA)', ' CA'),
 ('Sierra Nevada Brewing Company', 'Old Chico Crystal Wheat', 83, 'American Pale Wheat Ale', ' CA'),
 ('Sierra Nevada Brewing Company', 'Summerfest', 83, 'Czech Pilsener', ' CA'),
 ('Mission Brewery', 'Cortez Gold', 98, 'Belgian Pale Ale', ' CA'),
 ('Mission Brewery', 'Mission IPA', 98, 'American IPA', ' CA'),
 ('Mission Brewery', 'El Conquistador Extra Pale Ale', 98, 'American Pale Ale (APA)', ' CA'),
 ('Mission Brewery', 'Shipwrecked Double IPA', 98, 'American Double / Imperial IPA', ' CA'),
 ('Mother Earth Brew Company', "Cali Creamin'", 111, 'Cream Ale', ' CA'),
 ('Black Market Brewing Company', 'Deception', 112, 'American Blonde Ale', ' CA'),
 ('Black Market Brewing Company', 'Blackmarket Rye IPA', 112, 'American IPA', ' CA'),
 ('Black Market Brewing Company', 'Black Market Hefeweizen', 112, 'Hefeweizen', ' CA'),
 ('Black Market Brewing Company', 'Aftermath Pale Ale', 112, 'American Pale Ale (APA)', ' CA'),
 ('Anderson Valley Brewing Company', 'Blood Orange Gose', 171, 'Gose', ' CA'),
 ('Anderson Valley Brewing Company', "Keebarlin' Pale Ale", 171, 'American Pale Ale (APA)', ' CA'),
 ('Anderson Valley Brewing Company', 'the Kimmie, the Yink and the Holy Gose', 171, 'Gose', ' CA'),
 ('Anderson Valley Brewing Company', "Fall Hornin'", 171, 'Pumpkin Ale', ' CA'),
 ('Anderson Valley Brewing Company', 'Barney Flats Oatmeal Stout', 171, 'Oatmeal Stout', ' CA'),
 ('Anderson Valley Brewing Company', 'Summer Solstice', 171, 'Cream Ale', ' CA'),
 ('Anderson Valley Brewing Company', "Hop Ottin' IPA", 171, 'American IPA', ' CA'),
 ('Anderson Valley Brewing Company', 'Boont Amber Ale', 171, 'American Amber / Red Ale', ' CA'),
 ('Anderson Valley Brewing Company', 'El Steinber Dark Lager', 171, 'Vienna Lager', ' CA'),
 ('Anderson Valley Brewing Company', 'Boont Amber Ale (2010)', 171, 'American Amber / Red Ale', ' CA'),
 ('Anderson Valley Brewing Company', 'Summer Solstice Cerveza Crema (2009)', 171, 'Cream Ale', ' CA'),
 ('Anderson Valley Brewing Company', 'Barney Flats Oatmeal Stout (2012)', 171, 'Oatmeal Stout', ' CA'),
 ('Anderson Valley Brewing Company', 'Winter Solstice', 171, 'Winter Warmer', ' CA'),
 ('Anderson Valley Brewing Company', "Hop Ottin' IPA (2011)", 171, 'American IPA', ' CA'),
 ('Anderson Valley Brewing Company', 'Boont Amber Ale (2011)', 171, 'American Amber / Red Ale', ' CA'),
 ('Anderson Valley Brewing Company', 'Summer Solstice (2011)', 171, 'Cream Ale', ' CA'),
 ('Anderson Valley Brewing Company', 'Poleeko Gold Pale Ale (2009)', 171, 'American Pale Ale (APA)', ' CA'),
 ('Modern Times Beer', 'City of the Sun', 209, 'American IPA', ' CA'),
 ('Modern Times Beer', 'Booming Rollers', 209, 'American IPA', ' CA'),
 ('Modern Times Beer', 'Oneida', 209, 'American Pale Ale (APA)', ' CA'),
 ('Modern Times Beer', 'Aurora ', 209, 'American Amber / Red Ale', ' CA'),
 ('Modern Times Beer', 'Lomaland', 209, 'Saison / Farmhouse Ale', ' CA'),
 ('Modern Times Beer', 'Fortunate Islands', 209, 'American Pale Wheat Ale', ' CA'),
 ('Modern Times Beer', 'Black House', 209, 'American Stout', ' CA'),
 ('Modern Times Beer', 'Blazing World', 209, 'American Amber / Red Ale', ' CA'),
 ('Refuge Brewery', 'Blood Orange Wit', 225, 'Witbier', ' CA'),
 ('Golden Road Brewing', 'Might As Well IPL', 240, 'American Pale Lager', ' CA'),
 ('Golden Road Brewing', 'Saison Pamplemousse', 240, 'Saison / Farmhouse Ale', ' CA'),
 ('Golden Road Brewing', '2020 IPA', 240, 'American IPA', ' CA'),
 ('Golden Road Brewing', 'Wolf Among Weeds IPA', 240, 'American IPA', ' CA'),
 ('Golden Road Brewing', 'Better Weather IPA', 240, 'American IPA', ' CA'),
 ('Golden Road Brewing', 'Point the Way IPA', 240, 'American IPA', ' CA'),
 ('Golden Road Brewing', 'Golden Road Hefeweizen', 240, 'Hefeweizen', ' CA'),
 ('Golden Road Brewing', 'Heal the Bay IPA', 240, 'American IPA', ' CA'),
 ('Golden Road Brewing', 'Cabrillo KÃ¶lsch', 240, 'KÃ¶lsch', ' CA'),
 ('Golden Road Brewing', 'Get Up Offa That Brown', 240, 'American Brown Ale', ' CA'),
 ('Golden Road Brewing', 'Burning Bush Smoked IPA', 240, 'American IPA', ' CA'),
 ('Golden Road Brewing', 'Wolf Among Weeds IPA (2012)', 240, 'American IPA', ' CA'),
 ('Golden Road Brewing', 'Point the Way IPA (2012)', 240, 'American IPA', ' CA'),
 ('Golden Road Brewing', 'Golden Road Hefeweizen (2012)', 240, 'Hefeweizen', ' CA'),
 ('Santa Cruz Mountain Brewing', 'Giant DIPA', 252, 'American Double / Imperial IPA', ' CA'),
 ('Santa Cruz Mountain Brewing', 'Dread Brown Ale', 252, 'American Brown Ale', ' CA'),
 ('Santa Cruz Mountain Brewing', 'Casinos IPA', 252, 'English India Pale Ale (IPA)', ' CA'),
 ('Headlands Brewing Company', 'Groupe G', 280, 'Belgian IPA', ' CA'),
 ('Headlands Brewing Company', 'Pt. Bonita Rustic Lager', 280, 'American Pale Lager', ' CA'),
 ('Headlands Brewing Company', 'Hill 88 Double IPA', 280, 'American Double / Imperial IPA', ' CA'),
 ('Saint Archer Brewery', 'Saint Archer White Ale', 288, 'Witbier', ' CA'),
 ('Saint Archer Brewery', 'Saint Archer IPA', 288, 'American IPA', ' CA'),
 ('Saint Archer Brewery', 'Saint Archer Pale Ale', 288, 'American Pale Ale (APA)', ' CA'),
 ('Saint Archer Brewery', 'Saint Archer Blonde', 288, 'KÃ¶lsch', ' CA'),
 ('Pine Street Brewery', 'Black Bay Milk Stout', 310, 'Milk / Sweet Stout', ' CA'),
 ('Pine Street Brewery', 'Atom Splitter Pale Ale', 310, 'American Pale Ale (APA)', ' CA'),
 ('Claremont Craft Ales', 'Jacaranada Rye IPA', 320, 'American IPA', ' CA'),
 ("David's Ale Works", 'Sprocket Blonde Ale (2006)', 333, 'American Blonde Ale', ' CA'),
 ("David's Ale Works", 'Sprocket Pale Ale (2006)', 333, 'American Pale Ale (APA)', ' CA'),
 ('Manzanita Brewing Company', 'Chaotic Double IPA', 346, 'American Double / Imperial IPA', ' CA'),
 ('Manzanita Brewing Company', 'Manzanita IPA', 346, 'American IPA', ' CA'),
 ('Manzanita Brewing Company', 'Riverwalk Blonde Ale', 346, 'American Blonde Ale', ' CA'),
 ('Manzanita Brewing Company', 'Gillespie Brown Ale', 346, 'American Brown Ale', ' CA'),
 ('Manzanita Brewing Company', 'Manzanita Pale Ale', 346, 'American Pale Ale (APA)', ' CA'),
 ('Central Coast Brewing Company', 'Chai Ale', 350, 'Herbed / Spiced Beer', ' CA'),
 ('Central Coast Brewing Company', 'Lucky Day IPA', 350, 'American IPA', ' CA'),
 ('Central Coast Brewing Company', 'Terrace Hill Double IPA', 350, 'American Double / Imperial IPA', ' CA'),
 ('Central Coast Brewing Company', 'Catch 23', 350, 'American Black Ale', ' CA'),
 ('21st Amendment Brewery', 'He Said Baltic-Style Porter', 368, 'Baltic Porter', ' CA'),
 ('21st Amendment Brewery', 'He Said Belgian-Style Tripel', 368, 'Tripel', ' CA'),
 ('21st Amendment Brewery', 'Lower De Boom', 368, 'American Barleywine', ' CA'),
 ('21st Amendment Brewery', 'Fireside Chat', 368, 'Winter Warmer', ' CA'),
 ('21st Amendment Brewery', 'Marooned On Hog Island', 368, 'American Stout', ' CA'),
 ('21st Amendment Brewery', 'Bitter American', 368, 'American Pale Ale (APA)', ' CA'),
 ('21st Amendment Brewery', 'Hell or High Watermelon Wheat (2009)', 368, 'Fruit / Vegetable Beer', ' CA'),
 ('21st Amendment Brewery', '21st Amendment Watermelon Wheat Beer (2006)', 368, 'Fruit / Vegetable Beer', ' CA'),
 ('21st Amendment Brewery', '21st Amendment IPA (2006)', 368, 'American IPA', ' CA'),
 ('21st Amendment Brewery', 'Brew Free! or Die IPA (2008)', 368, 'American IPA', ' CA'),
 ('21st Amendment Brewery', 'Brew Free! or Die IPA (2009)', 368, 'American IPA', ' CA'),
 ('21st Amendment Brewery', 'Special Edition: Allies Win The War!', 368, 'English Strong Ale', ' CA'),
 ('21st Amendment Brewery', 'Hop Crisis', 368, 'American Double / Imperial IPA', ' CA'),
 ('21st Amendment Brewery', 'Bitter American (2011)', 368, 'American Pale Ale (APA)', ' CA'),
 ('21st Amendment Brewery', 'Fireside Chat (2010)', 368, 'Winter Warmer', ' CA'),
 ('21st Amendment Brewery', 'Back in Black', 368, 'American Black Ale', ' CA'),
 ('21st Amendment Brewery', "Monk's Blood", 368, 'Belgian Dark Ale', ' CA'),
 ('21st Amendment Brewery', 'Brew Free! or Die IPA', 368, 'American IPA', ' CA'),
 ('21st Amendment Brewery', 'Hell or High Watermelon Wheat', 368, 'Fruit / Vegetable Beer', ' CA'),
 ('Pizza Port Brewing Company', 'PONTO S.I.P.A.', 370, 'American IPA', ' CA'),
 ('Pizza Port Brewing Company', 'Chronic Ale', 370, 'American Amber / Red Ale', ' CA'),
 ('Pizza Port Brewing Company', "Swami's India Pale Ale", 370, 'American IPA', ' CA'),
 ('Ruhstaller Beer Company', '1881 California Red', 397, 'American Amber / Red Ale', ' CA'),
 ('Ruhstaller Beer Company', 'CAPT Black IPA', 397, 'American Black Ale', ' CA'),
 ('Ruhstaller Beer Company', "Ruhstaller's Gilt Edge Lager Beer", 397, 'American Amber / Red Lager', ' CA'),
 ('Ruhstaller Beer Company', '1881 California Red Ale', 397, 'American Amber / Red Ale', ' CA'),
 ('Hess Brewing Company', 'Grazias', 423, 'Cream Ale', ' CA'),
 ('Hess Brewing Company', 'Habitus IPA', 423, 'American IPA', ' CA'),
 ('Hess Brewing Company', 'Ex Umbris Rye Imperial Stout', 423, 'American Double / Imperial Stout', ' CA'),
 ('Seabright Brewery', 'Blur India Pale Ale', 432, 'American IPA', ' CA'),
 ('Mavericks Beer Company', 'Pit Stop Chocolate Porter', 448, 'American Porter', ' CA'),
 ('Mavericks Beer Company', 'Pace Setter Belgian Style Wit', 448, 'Witbier', ' CA'),
 ('Mavericks Beer Company', 'Back in the Saddle Rye Pale Ale', 448, 'American Pale Ale (APA)', ' CA'),
 ('TailGate Beer', 'Dodgy Knight Imperial IPA', 449, 'American Double / Imperial IPA', ' CA'),
 ('TailGate Beer', 'TailGate Saison', 449, 'Saison / Farmhouse Ale', ' CA'),
 ('TailGate Beer', 'TailGate IPA', 449, 'American IPA', ' CA'),
 ('TailGate Beer', 'TailGate Hefeweizen', 449, 'Hefeweizen', ' CA'),
 ('TailGate Beer', 'Blacktop Blonde', 449, 'American Blonde Ale', ' CA'),
 ('Armstrong Brewing Company', "Mo's Gose", 461, 'Gose', ' CA'),
 ('Hangar 24 Craft Brewery', 'Orange Wheat', 476, 'Fruit / Vegetable Beer', ' CA'),
 ('Hangar 24 Craft Brewery', 'Hangar 24 Helles Lager', 476, 'Munich Helles Lager', ' CA'),
 ("Devil's Canyon Brewery", 'Deadicated Amber', 491, 'American Amber / Red Ale', ' CA'),
 ("Devil's Canyon Brewery", 'California Sunshine Rye IPA', 491, 'American IPA', ' CA'),
 ("Devil's Canyon Brewery", 'Full Boar Scotch Ale', 491, 'Scotch Ale / Wee Heavy', ' CA'),
 ('Monkey Paw Pub & Brewery', 'Sweet Georgia Brown', 514, 'American Brown Ale', ' CA'),
 ('Monkey Paw Pub & Brewery', "Rich Man's IIPA", 514, 'American Double / Imperial IPA', ' CA'),
 ('Monkey Paw Pub & Brewery', 'Monkey Paw Oatmeal Pale Ale', 514, 'American Pale Ale (APA)', ' CA'),
 ("Butcher's Brewing", 'Mucho Aloha Hawaiian Pale Ale', 517, 'American Pale Ale (APA)', ' CA'),
 ('Uncommon Brewers', 'Scotty K NA', 522, 'Low Alcohol Beer', ' CA'),
 ('Uncommon Brewers', 'Bacon Brown Ale', 522, 'American Brown Ale', ' CA'),
 ('Uncommon Brewers', 'Golden State Ale', 522, 'Belgian Pale Ale', ' CA'),
 ('Uncommon Brewers', 'Baltic Porter', 522, 'Baltic Porter', ' CA'),
 ('Uncommon Brewers', 'Siamese twin', 522, 'Dubbel', ' CA'),
 ('Mammoth Brewing Company', 'High Country Pilsner (Current)', 534, 'German Pilsener', ' CA'),
 ('Mammoth Brewing Company', 'Epic IPA', 534, 'American IPA', ' CA'),
 ('Mammoth Brewing Company', 'Golden Trout Pilsner', 534, 'German Pilsener', ' CA'),
 ('Mammoth Brewing Company', 'Real McCoy Amber Ale (Current)', 534, 'American Amber / Red Ale', ' CA'),
 ('Ukiah Brewing Company', 'Pilsner Ukiah', 555, 'German Pilsener', ' CA')]

The distribution of the various beer names in CA in the join data of breweries and beers. 
Table appearing in the order of placement/arrangement of what were selected.
The DISTINCT FUNCTION ANLY AFFECTED THE BEER NAME. Thus, reducing the number of rows from 182 to 173.

In [49]:
%%sql

SELECT *
FROM breweries
LIMIT 10

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
10 rows affected.

[(0, 'NorthGate Brewing ', 'Minneapolis', ' MN'),
 (1, 'Against the Grain Brewery', 'Louisville', ' KY'),
 (2, "Jack's Abby Craft Lagers", 'Framingham', ' MA'),
 (3, 'Mike Hess Brewing Company', 'San Diego', ' CA'),
 (4, 'Fort Point Beer Company', 'San Francisco', ' CA'),
 (5, 'COAST Brewing Company', 'Charleston', ' SC'),
 (6, 'Great Divide Brewing Company', 'Denver', ' CO'),
 (7, 'Tapistry Brewing', 'Bridgman', ' MI'),
 (8, 'Big Lake Brewing', 'Holland', ' MI'),
 (9, 'The Mitten Brewing Company', 'Grand Rapids', ' MI')]

In [21]:
%%sql

SELECT state, city, brewery_name
FROM breweries
ORDER BY brewery_name DESC
LIMIT 3

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
3 rows affected.

[(' CO', 'Denver', 'Wynkoop Brewing Company'),
 (' OR', 'Bend', 'Worthy Brewing Company'),
 (' MA', 'Worcester', 'Wormtown Brewery')]

In [5]:
%%sql

SELECT city, state, COUNT(city) as num_of_city
FROM breweries
GROUP BY city, state
ORDER BY num_of_city DESC
LIMIT 10

Environment variable $DATABASE_URL not set, and no connect string given.
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

In [20]:
%%sql

SELECT state, city, COUNT(city) as num_of_city
FROM breweries
GROUP BY city, state
ORDER BY num_of_city DESC
LIMIT 3

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
3 rows affected.

[(' OR', 'Portland', 11), (' CO', 'Boulder', 9), (' IL', 'Chicago', 9)]

The above command helps to determine the frequency distribution of the Cities in the different State from the breweries data set.

%%sql

SELECT state, city, COUNT(city) as num_of_city
FROM breweries
GROUP BY city, state
ORDER BY num_of_city DESC

In [ ]:
%%sql

SELECT state, city, COUNT(city) as num_of_city
FROM breweries
GROUP BY city, state
ORDER BY num_of_city DESC

In [6]:
%%sql 

SELECT *
FROM beers
LIMIT 4

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
4 rows affected.

[(0, 0.05, None, 1436, 'Pub Beer', 'American Pale Lager', 408, 12.0),
 (1, 0.066, None, 2265, "Devil's Cup", 'American Pale Ale (APA)', 177, 12.0),
 (2, 0.071, None, 2264, 'Rise of the Phoenix', 'American IPA', 177, 12.0),
 (3, 0.09, None, 2263, 'Sinister', 'American Double / Imperial IPA', 177, 12.0)]

In [19]:
%%sql

SELECT brewery_id, beers_name, COUNT(beers_name) as num_of_beers_name
FROM beers
GROUP BY beers_name, brewery_id
ORDER BY num_of_beers_name DESC
LIMIT 3

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
3 rows affected.

[(80, 'Nonstop Hef Hop', 12),
 (439, 'Longboard Island Lager', 4),
 (166, "Dale's Pale Ale", 4)]

In [18]:
%%sql

SELECT beers.brewery_id, breweries.state, breweries.brewery_name, beers.beers_name, COUNT(beers.beers_name) as num_of_beers_name
FROM beers
INNER JOIN breweries
ON beers.brewery_id = breweries.brewery_id
GROUP BY beers.brewery_id, breweries.state, breweries.brewery_name, beers.beers_name
ORDER BY num_of_beers_name DESC
LIMIT 3

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
3 rows affected.

[(80, ' OR', 'Hopworks Urban Brewery', 'Nonstop Hef Hop', 12),
 (166, ' CO', 'Oskar Blues Brewery', "Dale's Pale Ale", 4),
 (439, ' HI', 'Kona Brewing Company', 'Longboard Island Lager', 4)]

Note: The combined data revealed that the beers (name) with the highest occurence is Nonstop Hef Hop with a frequency of 12 and it is produced by Hopworks Urban Brewery

In [17]:
%%sql

SELECT state, brewery_name, COUNT(brewery_name) as freq_of_brewery
FROM breweries
GROUP BY state, brewery_name
ORDER BY freq_of_brewery DESC
LIMIT 4

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
4 rows affected.

[(' VT', 'Otter Creek Brewing', 2),
 (' KY', 'Against the Grain Brewery', 2),
 (' MN', 'Summit Brewing Company', 2),
 (' PA', 'Sly Fox Brewing Company', 2)]

In [15]:
%%sql

SELECT *
FROM breweries
LIMIT 3

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
3 rows affected.

[(0, 'NorthGate Brewing ', 'Minneapolis', ' MN'),
 (1, 'Against the Grain Brewery', 'Louisville', ' KY'),
 (2, "Jack's Abby Craft Lagers", 'Framingham', ' MA')]

In [23]:
%%sql

SELECT state, brewery_name, COUNT(state) as freq_of_state
FROM breweries
GROUP BY state, brewery_name
ORDER BY freq_of_state DESC
LIMIT 4

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
4 rows affected.

[(' VT', 'Otter Creek Brewing', 2),
 (' KY', 'Against the Grain Brewery', 2),
 (' MN', 'Summit Brewing Company', 2),
 (' PA', 'Sly Fox Brewing Company', 2)]

In [27]:
%%sql

SELECT state, COUNT(state) as freq_of_state
FROM breweries
GROUP BY state
ORDER BY freq_of_state DESC
LIMIT 4

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
4 rows affected.

[(' CO', 47), (' CA', 39), (' MI', 32), (' OR', 29)]

In [32]:
%%sql

SELECT breweries.brewery_id, breweries.brewery_name, COUNT(beers.beers_name) as freq_of_beers_name
FROM beers
INNER JOIN breweries
ON beers.brewery_id = breweries.brewery_id
GROUP BY breweries.brewery_name, breweries.brewery_id
ORDER BY freq_of_beers_name DESC
LIMIT 3

 * mysql+pymysql://root:***@127.0.0.1:3306/beers
3 rows affected.

[(10, 'Brewery Vivant', 60),
 (25, 'Sun King Brewing Company', 36),
 (166, 'Oskar Blues Brewery', 29)]

Note: Above is the Brewery with the highest frequency of beers in the joined data set.